#!/bin/bash

# mruserpwd : MariaDB/MySQL Normal User Password Reset
#
# Usage     : bash mruserpwd
#
# (c) 2023 - 2024. David Eleazar

# ANSI colors
NC='\033[0m'
BLACK='\033[0;30m'
RED='\033[0;31m'
GREEN='\033[0;32m'
BROWN='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LGRAY='\033[0;37m'
DGRAY='\033[1;30m'
LRED='\033[1;31m'
LGREEN='\033[1;32m'
YELLOW='\033[1;33m'
LBLUE='\033[1;34m'
LPURPLE='\033[1;35m'
LCYAN='\033[1;36m'
WHITE='\033[1;37m'

function version {
  echo "$@" | awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }';
}

function get_update_plugin_query {
  local USER=$1
  local PLUGIN=$2

  echo 'UPDATE `mysql`.`user` SET `plugin` = "'$PLUGIN'" WHERE `user`="'$USER'";'
}

function build_pwd_reset_query() {
  local DB=$1
  local VERSION=$2
  local USERNAME=$3
  local PASSWORD=$4

  local FLUSH_QUERY='FLUSH PRIVILEGES;'

  if [ "$DB" == "MariaDB" ]; then
    # Dealing with MariaDB database
    if [ $(version "$VERSION") -lt $(version "10.2") ]; then
      # This query works on MariaDB prior to 10.2
      # Warning: this reset query involved low level hacks
      local CLEAR=$(get_update_plugin_query $USERNAME)
      local RESET_PWD='UPDATE `mysql`.`user` SET `password` = PASSWORD("'$PASSWORD'") WHERE `user`="'$USERNAME'";'
      local RESTORE=$(get_update_plugin_query $USERNAME mysql_native_password)
      local BUILT_QUERY="${FLUSH_QUERY} ${CLEAR} ${FLUSH_QUERY} ${RESET_PWD} ${FLUSH_QUERY} ${RESTORE} ${FLUSH_QUERY}"
    elif [[ $(version "$VERSION") -ge $(version "10.2") && $(version "$VERSION") -lt $(version "10.4") ]]; then
      # This query works on MariaDB 10.2+
      local RESET_PWD='ALTER USER `'$USERNAME'`@`localhost` IDENTIFIED BY "'$PASSWORD'";'
      local BUILT_QUERY="${FLUSH_QUERY} ${RESET_PWD} ${FLUSH_QUERY}"
    else
      # This mode works on MariaDB 10.4+, which by default using dual authentication plugins:
      # 'mysql_native_password' and 'unix_socket'
      # This method is preferred method for modern MariaDB 10.4+ installations
      local RESET_PWD='ALTER USER `'$USERNAME'`@`localhost` IDENTIFIED VIA mysql_native_password USING PASSWORD("'$PASSWORD'") OR unix_socket;'
      local BUILT_QUERY="${FLUSH_QUERY} ${RESET_PWD} ${FLUSH_QUERY}"
    fi
  else
    # Dealing with MySQL database
    if [ $(version "$VERSION") -lt $(version "5.7") ]; then
      # This query works on old MySQL (<5.7)
      local RESET_PWD='SET PASSWORD FOR `'$USERNAME'`@`localhost` = PASSWORD("'$PASSWORD'");'
      local BUILT_QUERY="${FLUSH_QUERY} ${RESET_PWD} ${FLUSH_QUERY}"
    else
      # This query works on newer MySQL (5.7+)
      local RESET_PWD='ALTER USER `'$USERNAME'`@`localhost` IDENTIFIED BY "'$PASSWORD'";'
      local BUILT_QUERY="${FLUSH_QUERY} ${RESET_PWD} ${FLUSH_QUERY}"
    fi
  fi

  # Return the result
  echo $BUILT_QUERY
}

function reset_user_password() {
  local DB=$(echo $1 | awk -F':' '{print $1}')
  local VERSION=$(echo $1 | awk -F':' '{print $2}')
  local USERNAME=$2
  local PASSWORD=$3
  local ROOT_PASSWORD=$4

  local QUERY=$(build_pwd_reset_query $DB $VERSION $USERNAME $PASSWORD)

  # For debugging only
  # echo $QUERY

  echo -e "Resetting ${CYAN}${DB}${NC} ${YELLOW}${USERNAME}${NC}'s password . . ."
  local RESULT=$(mysql -u root -p$ROOT_PASSWORD -e "$QUERY" 2>&1 | grep ERROR)

  # For debugging only
  # echo $RESULT
  # read -p "Press any key to continue . . ."

  if [ "$RESULT" == "" ]
  then
    echo -e "Done reset password! Your new ${YELLOW}${USERNAME}${NC}'s password is : ${GREEN}${PASSWORD}${NC}"
  else
    echo -e "${LRED}Failed to change ${YELLOW}${USERNAME}${LRED}'s password. Please try again.${NC}"
  fi
}

# --- Main function execution ---

# Check for non-root privileges
# Will warning of this script executed as root
if [ "$(id -u)" == "0" ]; then
  echo -e "${YELLOW}Warning: You are running this script as root.${NC}"
  echo -e "${YELLOW}Only ${LBLUE}normal privilege${YELLOW} needed. ${LRED}Use with caution!${NC}"
fi

IS_MARIADB=$(mysql --version | grep MariaDB)
VERSION_NUMBER=$(mysql --version | perl -pe '($_)=/([0-9]+([.][0-9]+)+([.][0-9]+)+)/')

if [ "$IS_MARIADB" != "" ]; then
  DB=MariaDB
else
  DB=MySQL
fi

echo -e "Your ${CYAN}${DB}${NC} version is ${YELLOW}${VERSION_NUMBER}${NC}"
read -p "Enter $(echo -e ${CYAN}${DB}${NC}) username : " DB_USERNAME
read -s -p "Enter $(echo -e ${CYAN}${DB}${NC}) new password : " DB_PASSWORD
echo
read -s -p "Re-enter $(echo -e ${CYAN}${DB}${NC}) new password : " DB_PASSWORD_CONF
echo

if [ "$DB_PASSWORD" == "$DB_PASSWORD_CONF" ]
then
  echo -e "${LBLUE}Password match. Proceeding . . .${NC}"
  read -s -p "Please enter $(echo -e ${LRED}root${NC}) password to continue : " ROOT_PASSWORD
  echo
  reset_user_password "${DB}:${VERSION_NUMBER}" $DB_USERNAME $DB_PASSWORD $ROOT_PASSWORD
  echo -e "${LGREEN}Reset password completed.${NC}"
  exit 0
else
  echo -e "${LRED}Password mismatch! Exiting . . .${NC}"
  exit 2
fi
