#!/bin/bash

# mruserpwd : MariaDB/MySQL Normal User Password Reset
#
# Usage     : bash mruserpwd
#
# (c) 2023. David Eleazar

# ANSI colors
NC='\033[0m'
BLACK='\033[0;30m'
RED='\033[0;31m'
GREEN='\033[0;32m'
BROWN='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LGRAY='\033[0;37m'
DGRAY='\033[1;30m'
LRED='\033[1;31m'
LGREEN='\033[1;32m'
YELLOW='\033[1;33m'
LBLUE='\033[1;34m'
LPURPLE='\033[1;35m'
LCYAN='\033[1;36m'
WHITE='\033[1;37m'

function version {
  echo "$@" | awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }';
}

function get_pwd_reset_query() {
  local DB=$1
  local VERSION=$2
  local USERNAME=$3
  local PASSWORD=$4

  if [ "$DB" == "MariaDB" ]
  then
    # Dealing with MariaDB database
    echo 'SET PASSWORD FOR `'$USERNAME'`@`localhost` = PASSWORD("'$PASSWORD'");'
  else
    # Dealing with MySQL database
    if [ $(version "$VERSION") -lt $(version "5.7") ]; then
      # This query works on old MySQL (< 5.7)
      echo 'SET PASSWORD FOR `'$USERNAME'`@`localhost` = PASSWORD("'$PASSWORD'");'
    else
      # This query works on newer MySQL (5.7 +)
      echo 'ALTER USER `'$USERNAME'`@`localhost` IDENTIFIED BY "'$PASSWORD'";'
    fi
  fi
}

function reset_user_password() {
  local DB=$(echo $1 | awk -F':' '{print $1}')
  local VERSION=$(echo $1 | awk -F':' '{print $2}')
  local USERNAME=$2
  local PASSWORD=$3
  local ROOT_PASSWORD=$4

  ALTER_QUERY=$(get_pwd_reset_query $DB $VERSION $USERNAME $PASSWORD)
  FLUSH_QUERY='FLUSH PRIVILEGES;'
  SQL="${FLUSH_QUERY} ${ALTER_QUERY} ${FLUSH_QUERY}"

  # For debugging only
  # echo $SQL

  echo -e "Resetting ${CYAN}${DB}${NC} ${YELLOW}${USERNAME}${NC}'s password . . ."
  RESULT=$(mysql -u root -p$ROOT_PASSWORD -e "$SQL" 2>&1)

  if [ "$RESULT" == "" ]
  then
    echo -e "Done reset password! Your new ${YELLOW}${USERNAME}${NC}'s password is : ${GREEN}${PASSWORD}${NC}"
  else
    echo -e "${LRED}Failed to change ${YELLOW}${USERNAME}${LRED}'s password. Please try again.${NC}"
  fi
}

# Main function execution
IS_MARIADB=$(mysql --version | grep MariaDB)
VERSION_NUMBER=$(mysql --version | perl -pe '($_)=/([0-9]+([.][0-9]+)+([.][0-9]+)+)/')

if [ "$IS_MARIADB" != "" ]; then
  DB=MariaDB
else
  DB=MySQL
fi

echo -e "Your ${CYAN}${DB}${NC} version is ${YELLOW}${VERSION_NUMBER}${NC}"
read -p "Enter $(echo -e ${CYAN}${DB}${NC}) username : " DB_USERNAME
read -s -p "Enter $(echo -e ${GREEN}${DB}${NC}) new password : " DB_PASSWORD
echo
read -s -p "Re-enter $(echo -e ${GREEN}${DB}${NC}) new password : " DB_PASSWORD_CONF
echo

if [ "$DB_PASSWORD" == "$DB_PASSWORD_CONF" ]
then
  echo -e "${LBLUE}Password match. Proceeding . . .${NC}"
  read -s -p "Please enter root password to continue : " ROOT_PASSWORD
  echo
  reset_user_password "${DB}:${VERSION_NUMBER}" $DB_USERNAME $DB_PASSWORD $ROOT_PASSWORD
else
  echo -e "${LRED}Password mismatch! Exiting . . .${NC}"
fi
